services:
  lgtm:
    image: docker.io/grafana/otel-lgtm:0.11.4
    container_name: lgtm
    ports:
      - "3000:3000"
      # - "4317:4317"
      - "14318:14318"
      - "9090:9090"
    volumes:
      - ./otel-lgtm/grafana:/data/grafana
      - ./otel-lgtm/prometheus:/data/prometheus
      - ./otel-lgtm/loki:/data/loki
      - ./otelcol-config.yaml:/otel-lgtm/otelcol-config.yaml
    environment:
      - GF_PATHS_DATA=/data/grafana
      - ENABLE_LOGS_PROMETHEUS="true"
      - ENABLE_LOGS_OTELCOL="true"
    # env_file:
    #   - .env
    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      - observability-demo

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    networks:
      - observability-demo

networks:
  observability-demo:
    name: observability-demo
    driver: bridge
